name: Dogtags
main: fromgate.dogtags.Dogtags
version: 0.0.5
load: POSTWORLD
author: fromgate, fromgate@gmail.com
commands:
   dogtag:
      description: Dogtags command
      usage: |
           /dogtag <help>   
           